### ISSUE TITLE
save_plot csv when sf

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/subfoldr#7]
When plots use sf data.frames, save_plot fails unless arg `csv = F`
error:
```
> save_plot("count", caption = "Snorkel count coverage by year and bank")
Error: is.data.frame(x) is not TRUE
```

**Comment by joethorley** [comment]
It seems to work on my machine
```
> source("plot-visit.R")
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 
> 
```

You will need to update your packages - probably easiest through PoisCRAN

**Comment by sebdalgarno** [comment]
I have updated packages and still get the same error.
I think `source("plot-visit.R")` worked in your case because of the `csv = F` argument in 
`save_plot("count", caption = "Snorkel count coverage by year and bank", csv = F)`.

Please try with `csv = F` deleted

**Comment by sebdalgarno** [comment]
A simple fix here would be:
```
if (csv)
    if(inherits(plot$data, "data.frame")) readr::write_csv(plot$data, path = file)
```
even if `csv = T` the function first checks whether `plot$data` is actually a `data.frame`

**Comment by joethorley** [comment]
great - can you implement

**Comment by sebdalgarno** [comment]
done
